[package]
name = "rmt2cc7800"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.14"
clap = { version = "4", features = ["derive"] }
